### ISSUE TITLE
Write tests for the API or nuke it?

### ISSUE THREAD

**Issue by dblock** [andrewvy/slack-pongbot#40]
We also need to write API tests or nuke'em. Also good opportunity to review the vocabulary, `rankings` are really `players` and `matches` are really `challenges`. Maybe we should just call them that? 

If we're going to be serious about an API, maybe it should have a Hypermedia layout.

**Comment by andrewvy** [comment]
I like the API idea, but perhaps it's smarter to not have it be one of the main focuses for now.

**Comment by dblock** [comment]
I agree @andrewvy, I say nuke it? Want to do just do it?

**Comment by dblock** [comment]
@andrewvy I am going to rewrite this API as a hypermedia one, building upon your work on the branch, unless you feel strongly about it.

**Comment by andrewvy** [comment]
Go for it, if you want. :+1:

I'd rather not remove it. :)

**Comment by dblock** [comment]
Closed via https://github.com/andrewvy/slack-pongbot/pull/57.
