### ISSUE TITLE
CORS for API calls

### ISSUE THREAD

**Issue by ryanluton** [andrewvy/slack-pongbot#68]
Have you thought about enabling cross-origin calls API calls at all? 

I spent a little time tonight trying to use the Express CORS middleware, but for some reason kept failing. Have you thought about this at all, or do you have any suggestions? -- Thanks

**Comment by dblock** [comment]
I don't see why it wouldn't work. Try to PR something and we'll help you fix it.

**Comment by ryanluton** [comment]
I ended up just adding the CORS header to all responses. 

Going to go ahead and close this without a PR. Thanks! great little app, am building a nice dash from the API that lives on a TV next to our office tables. 

```  
app.use(function(req, res, next) {
    res.setHeader("Access-Control-Allow-Origin", "*");
    return next();
});
```

**Comment by dblock** [comment]
I'd love a dashboard implementation that works with https://github.com/dblock/slack-gamebot (it evolved from this project and was rewritten in Ruby) too!
