### ISSUE TITLE
Running web view on heroku

### ISSUE THREAD

**Issue by danrosenthal** [andrewvy/slack-pongbot#75]
I have pongbot successfully configured on heroku at [this address](http://rndpxl-pongbot.herokuapp.com/). But, it's currently only showing up as raw json. I'm a little new to running apps on heroku, and I'm wondering what I need to do to get the web view to show up with all the player data.

What am I missing? Thanks for your help, and for building this. It's awesome.

**Comment by danrosenthal** [comment]
When I run `node app.js` locally I get an error.

![screen shot 2015-11-12 at 5 12 32 pm](https://cloud.githubusercontent.com/assets/1403188/11132901/a292e168-8960-11e5-864a-a42e6c2facbc.png)

**Comment by andrewvy** [comment]
I'm not sure about the mongo issue with NodeJS, but you should be able to access the web view through `/info` :) http://rndpxl-pongbot.herokuapp.com/info
