### ISSUE TITLE
Mention Pinpon in the README

### ISSUE THREAD

**Issue by mihar** [andrewvy/slack-pongbot#79]
We'd appreciate a mention of Pinpon in the deprecation notice as well. We're up and running for beta customers and will launch publicly soon.

It's the easiest way out there to get a ping pong bot going in Slack.

**Comment by andrewvy** [comment]
PR me with what you want! I'll be happy to show alternatives. Maybe..

"For a more complete, and commercial alternative, you can check out [Pinpon](https://pinpon.co/)."
