### ISSUE TITLE
Pongbot challenge not working

### ISSUE THREAD

**Issue by thmsmtylr** [andrewvy/slack-pongbot#9]
Hi there just setup your app with our Slack channel and get the following issue:

- Successfully registered! Welcome to the system, thmsmtylr. 
- Successfully registered! Welcome to the system, jason.

"pongbot challenge single @jason"

- Could not find a player with that name. Have they registered?

DB: 
```
[{"_id":"54f9314191ee2a0300766f38","user_name":"thmsmtylr","wins":0,"losses":0,"elo":0,"tau":0,"__v":0},{"_id":"54f9317691ee2a0300766f39","user_name":"jason","wins":0,"losses":0,"elo":0,"tau":0,"__v":0}]
```

Everything looks to be functioning correctly but I can't seem to get the challenge feature to work. Anything I'm overlooking here?

**Comment by andrewvy** [comment]
Hey, thanks for the issue!

I refrained from doing it the slack @mention way, so it wouldn't annoyingly notify the user with a ping pong battle. Just without the `@`, and just their username should work perfectly.

I'll add an option in the future to toggle/allow this type of referencing. :)

**Comment by thmsmtylr** [comment]
No worries mate, thanks for sharing :+1: 

I thought that was the case  however, using username doesn't work either unfortunately: 
- pongbot challenge single jason (returns nothing)

I might add this feature and issue a pull request.

**Comment by megatron-me-uk** [comment]
I think this should be fixed by pull request https://github.com/andrewvy/slack-pongbot/pull/10

**Comment by thmsmtylr** [comment]
@megatron-me-uk indeed it does, beat me too it! Thank you.

**Comment by andrewvy** [comment]
Thanks @megatron-me-uk for the fix. :)
